### ISSUE TITLE
apache config for UCS 4.2

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-ucs#2]
To run on UCS 4.2 we need to rename

/etc/apache2/sites-available/privacyidea

to

/etc/apache2/sites-available/privacyidea.conf

**Comment by spaceone** [comment]
You can add a debian/privacyidea-blah.maintscript file containting 
mv_conffile /etc/univention/templates/files/etc/apache2/sites-available/privacyidea /etc/univention/templates/files/etc/apache2/sites-available/privacyidea 9.0.0~

Where 9.0.0 is the number of your package.

**Comment by cornelinux** [comment]
But 2.18.1 is the name of my package for UCS 4.1 and also for UCS 4.2. ?

**Comment by spaceone** [comment]
The .conf suffix will also work with UCS 4.1

**Comment by cornelinux** [comment]
touché. Thought so. Thanks!

**Comment by spaceone** [comment]
I think this should work: https://github.com/NetKnights-GmbH/privacyidea-ucs/pull/3

**Comment by cornelinux** [comment]
I would like to check this, but I also have the problem:

>  privacyidea-ucs : Hängt ab von: mysql-server \ 
>                       soll aber nicht installiert werden
>                    Hängt ab von: libapache2-mod-wsgi \
>                       soll aber nicht installiert werden

...was also forwarded to Dirk...

**Comment by spaceone** [comment]
What does "apt-get install mysql-server" say? It should show you the new package name. You can then add a dependency with "OR" similar to somehting like "Depends: mysql-server | mysql-5.5-server".

**Comment by spaceone** [comment]
Or you just move to postgres :D ;-)

**Comment by cornelinux** [comment]
Unfortunately it does not:

<pre>
# apt-get install mysql-server
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt-get -f install«, um dies zu korrigieren:
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 mysql-server : Hängt ab von: mysql-server-5.5 soll aber nicht installiert werden
 privacyidea-ucs : Hängt ab von: libapache2-mod-wsgi soll aber nicht installiert werden
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt-get -f install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
</pre>

**Comment by cornelinux** [comment]
I'll move to mongodb or redis! ;-)

**Comment by spaceone** [comment]
You have to continue this, with 'apt-get install mysql-server-5.5'. and so on. This will somewhen then show you the real broken package.

**Comment by cornelinux** [comment]
To me this looks a bit circular:

<pre>
root@douglasadams:~# apt install mysql-server
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt-get -f install«, um dies zu korrigieren:
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 mysql-server : Hängt ab von: mysql-server-5.5 soll aber nicht installiert werden
 privacyidea-ucs : Hängt ab von: libapache2-mod-wsgi soll aber nicht installiert werden
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt-get -f install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
root@douglasadams:~# apt-get install mysql-server
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt-get -f install«, um dies zu korrigieren:
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 mysql-server : Hängt ab von: mysql-server-5.5 soll aber nicht installiert werden
 privacyidea-ucs : Hängt ab von: libapache2-mod-wsgi soll aber nicht installiert werden
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt-get -f install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
root@douglasadams:~# apt install mysql-server-5.5
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt-get -f install«, um dies zu korrigieren:
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 privacyidea-ucs : Hängt ab von: mysql-server soll aber nicht installiert werden
                   Hängt ab von: libapache2-mod-wsgi soll aber nicht installiert werden
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt-get -f install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
root@douglasadams:~# apt install libapache2-mod-wsgi
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Probieren Sie »apt-get -f install«, um dies zu korrigieren:
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 privacyidea-ucs : Hängt ab von: mysql-server soll aber nicht installiert werden
E: Unerfüllte Abhängigkeiten. Versuchen Sie »apt-get -f install« ohne Angabe eines Pakets (oder geben Sie eine Lösung an).
root@douglasadams:~# 

</pre>

Are this limitation by any ucs packages?

**Comment by cornelinux** [comment]
This is resolved.
