### ISSUE TITLE
Support UCS 4.3

### ISSUE THREAD

**Issue by cornelinux** [NetKnights-GmbH/privacyidea-ucs#7]
Do it!

**Comment by cornelinux** [comment]
We will build 2.23.1, when it is released for 4.3 in about a week.

**Comment by bjo81** [comment]
privacaidea-pam is missing for 4.3, but I think the version for 4.2 could be easily used.

**Comment by cornelinux** [comment]
There is an extra repository for privacyidea-pam https://github.com/NetKnights-GmbH/privacyidea-ucs-pam
But I think next to the RADIUS plugin and SAML plugin, the PAM module is imho the least important one.

**Comment by bjo81** [comment]
Ok, created an issue in the extra repo: https://github.com/NetKnights-GmbH/privacyidea-ucs-pam/issues/1

**Comment by cornelinux** [comment]
thx. We have done it for PI. So I close this issue.
